module.exports = {
  apps: [
    {
      name: 'tradooor-backend',
      script: 'pnpm',
      args: '--filter backend start',
      cwd: '/opt/tradooor',
      env_file: '/opt/tradooor/apps/backend/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/backend-error.log',
      out_file: './logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      instances: 1,
    },
    {
      name: 'tradooor-frontend',
      script: 'pnpm',
      args: '--filter frontend start',
      cwd: '/opt/tradooor',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
      },
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      instances: 1,
    },
    {
      name: 'tradooor-metrics-worker',
      script: 'pnpm',
      args: '--filter backend metrics:cron',
      cwd: '/opt/tradooor',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/metrics-worker-error.log',
      out_file: './logs/metrics-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
    },
    {
      name: 'tradooor-trade-worker',
      script: 'pnpm',
      args: '--filter backend worker:normalized-trades',
      cwd: '/opt/tradooor',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/trade-worker-error.log',
      out_file: './logs/trade-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
    },
  ],
};
